### ISSUE TITLE
I meet a same error, how do you to fix it?

### ISSUE THREAD

**Issue by yaonie084** [kylefinley/PM2-coffee-test#1]
server-0 (err): SyntaxError: Unexpected string
server-0 (err):     at Module._compile (module.js:439:25)
server-0 (err):     at Object.Module._extensions..js (module.js:474:10)
server-0 (err):     at Module.load (module.js:356:32)
server-0 (err):     at Function.Module._load (module.js:312:12)
server-0 (err):     at Function.Module.runMain (module.js:497:10)
server-0 (err):     at startup (node.js:119:16)
server-0 (err):     at node.js:906:3
server-1 (err): SyntaxError: Unexpected string
server-1 (err):     at Module._compile (module.js:439:25)
server-1 (err):     at Object.Module._extensions..js (module.js:474:10)
server-1 (err):     at Module.load (module.js:356:32)
server-1 (err):     at Function.Module._load (module.js:312:12)
server-1 (err):     at Function.Module.runMain (module.js:497:10)
server-1 (err):     at startup (node.js:119:16)
server-1 (err):     at node.js:906:3
server-1 (err): /Users/ethanwang/node/custom/hack_test/server.coffee:1
server-1 (err): ction (exports, require, module, __filename, __dirname) { _ = require 'lodash'

**Comment by kylefinley** [comment]
@yaonie084,

You have to specify the `--interpreter`:

```
$ pm2 start server.coffee --interpreter coffee
```

https://github.com/Unitech/PM2/issues/488#issuecomment-68023008
